
[run_params]
connector="board_em"
strategy="random"
ai_color="white"

[connector.board_em]
hostname="demo.mattmerr.com"
game_id="a267cea3-aa11-43ae-87c3-55a347ffeeb5"
poll_rate=1500

[connector.ipc]
game_id="hello_world_game"

[strategy.random]
seed="12345"
